version: '3'
services:
  order-service:
    image: openjdk:11
    ports:
    - 8080
    extra_hosts:
      - docker.host.internal:host-gateway
    environment:
      - nacos_host=http://docker.host.internal:8848
      - nacos_password=a123456a
    volumes:
    - ./:/home/order
    command: java -jar /home/order/uber-order-service-0.0.1-SNAPSHOT.jar --spring.profiles.active=prod

networks:
  default:
    name: uber_default