spring:
  application:
    name: uber-order-service
  cloud:
    nacos:
      server-addr: http://localhost:8848
      discovery:
        namespace: public

logging:
  level:
    root: info
    com:
      example: debug
  pattern:
    console: '%-5level %C.%M[%line] - %msg%n'
