spring:
  application:
    name: user-service
  cloud:
    nacos:
      server-addr: http://localhost:8848
      discovery:
        namespace: public
server:
  port: 8082 # 避免服务冲突

logging:
  level:
    root: info
    com:
      example: debug
  pattern:
    console: '%-5level %C.%M[%line] - %msg%n'
